name: flutter_graphql_with_ferry
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  cupertino_icons: ^1.0.2
  ferry: ^0.11.0+1
  ferry_flutter: ^0.6.1+1
  ferry_hive_store: ^0.4.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  gql_http_link: ^0.4.0
  gql_link: ^0.5.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.0-dev.9
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  path_provider: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  ferry_generator: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true
